import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { Alert, Button, Card, CardContent, CardHeader, Input, Table, TableCell, TableHead, TableHeader, TableRow, Tabs, TabsContent, TabsList, TabsTrigger } from '@/design-system'
import { hasPermission } from '@/features/identity/permissions'
import { documentsApi, type Customer, type Invoice } from './documents-api'

export function ReceivablesPage() {
  const canRead = hasPermission('receivables.customers.read') || hasPermission('receivables.invoices.read'); const canManage = hasPermission('receivables.customers.manage'); const canCreate = hasPermission('receivables.invoices.create'); const canIssue = hasPermission('receivables.invoices.issue'); const canVoid = hasPermission('receivables.invoices.void')
  const [customers,setCustomers]=useState<Customer[]>([]);const [invoices,setInvoices]=useState<Invoice[]>([]);const [message,setMessage]=useState<string|null>(null)
  const load=useCallback(async()=>{try{const [c,i]=await Promise.all([documentsApi.customers(),documentsApi.invoices()]);setCustomers(c.data.customers);setInvoices(i.data.invoices)}catch(error){setMessage(error instanceof Error?error.message:'Unable to load receivables.')}},[])
  useEffect(()=>{if(canRead)void load()},[canRead,load])
  async function openPdf(invoice: Invoice) { try { const blob = await documentsApi.invoicePdf(invoice); const url = URL.createObjectURL(blob); window.open(url, '_blank', 'noopener,noreferrer'); window.setTimeout(() => URL.revokeObjectURL(url), 60_000) } catch (error) { setMessage(error instanceof Error ? error.message : 'PDF retrieval failed.') } }
  async function editInvoice(invoice: Invoice) { const notes = window.prompt('Replace draft notes (leave blank for none):', ''); if (notes === null) return; try { await documentsApi.updateInvoice(invoice, { notes: notes || null }); await load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Draft update failed.') } }
  async function voidInvoice(invoice: Invoice) {
    const reasonCode = window.prompt('Configured void reason code:', ''); if (!reasonCode) return
    const narrative = window.prompt('Void narrative:', ''); if (!narrative) return
    try {
      const result = await documentsApi.voidInvoice(invoice, { void_date: new Date().toISOString().slice(0, 10), reason_code: reasonCode, narrative })
      setMessage(result.status === 202 && result.data.approval ? `Approval ${result.data.approval.id} is pending; the invoice remains posted.` : 'Invoice voided.')
      await load()
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Void failed.') }
  }
  if(!canRead)return <main className="p-6"><Alert>You do not have permission to view receivables.</Alert></main>
  return <main className="p-6"><div className="mx-auto max-w-6xl space-y-5"><div><h1 className="text-2xl font-semibold">Receivables</h1><p className="text-sm text-[var(--color-text-muted)]">Customer masters and invoice drafting, issue, void, and PDF access.</p></div>{message?<Alert>{message}</Alert>:null}<Tabs defaultValue="invoices"><TabsList><TabsTrigger value="invoices">Invoices</TabsTrigger><TabsTrigger value="customers">Customers</TabsTrigger></TabsList><TabsContent value="invoices" className="space-y-4">{canCreate?<InvoiceForm customers={customers} onDone={load} onError={setMessage}/>:null}<Card><CardContent><Table><TableHeader><TableRow><TableHead>Number</TableHead><TableHead>Date</TableHead><TableHead>Status</TableHead><TableHead>Total</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><tbody>{invoices.map(i=><TableRow key={i.id}><TableCell>{i.document_number??'Draft'}</TableCell><TableCell>{i.invoice_date}</TableCell><TableCell>{i.status}</TableCell><TableCell>{i.total.currency} {i.total.amount}</TableCell><TableCell className="space-x-2">{i.status==='draft'&&canCreate?<Button variant="secondary" onClick={()=>void editInvoice(i)}>Edit</Button>:null}{i.status==='draft'&&canIssue?<Button variant="secondary" onClick={()=>void documentsApi.issueInvoice(i).then(load).catch(e=>setMessage(e instanceof Error?e.message:'Issue failed'))}>Issue</Button>:i.status==='sent'?<Button variant="secondary" onClick={()=>void openPdf(i)}>PDF</Button>:null}{(i.status==='draft'||i.status==='sent')&&canVoid?<Button variant="danger" onClick={()=>void voidInvoice(i)}>Void</Button>:null}</TableCell></TableRow>)}</tbody></Table></CardContent></Card></TabsContent><TabsContent value="customers" className="space-y-4">{canManage?<CustomerForm onDone={load} onError={setMessage}/>:null}<Card><CardContent><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Type</TableHead><TableHead>Currency</TableHead><TableHead>Status</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><tbody>{customers.map(c=><TableRow key={c.id}><TableCell>{c.name}</TableCell><TableCell>{c.type}</TableCell><TableCell>{c.default_currency}</TableCell><TableCell>{c.status}</TableCell><TableCell>{c.status==='active'&&canManage?<Button variant="secondary" onClick={()=>void documentsApi.deactivateCustomer(c).then(load).catch(e=>setMessage(e instanceof Error?e.message:'Deactivation failed'))}>Deactivate</Button>:null}</TableCell></TableRow>)}</tbody></Table></CardContent></Card></TabsContent></Tabs></div></main>
}

function CustomerForm({onDone,onError}:{onDone:()=>Promise<void>;onError:(value:string|null)=>void}){const [name,setName]=useState('');const [currency,setCurrency]=useState('');const [terms,setTerms]=useState('');async function submit(e:FormEvent){e.preventDefault();try{await documentsApi.createCustomer({name,type:'local',default_currency:currency,payment_terms:terms});setName('');await onDone()}catch(error){onError(error instanceof Error?error.message:'Customer creation failed.')}}return <Card><CardHeader><h2 className="font-semibold">Create customer</h2></CardHeader><CardContent><form className="grid gap-3 md:grid-cols-4" onSubmit={submit}><Input placeholder="Name" value={name} onChange={e=>setName(e.target.value)} required/><Input placeholder="Currency" value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} required/><Input placeholder="Configured terms key" value={terms} onChange={e=>setTerms(e.target.value)} required/><Button type="submit">Create</Button></form></CardContent></Card>}
function InvoiceForm({customers,onDone,onError}:{customers:Customer[];onDone:()=>Promise<void>;onError:(value:string|null)=>void}){const [customer,setCustomer]=useState('');const [date,setDate]=useState('');const [description,setDescription]=useState('');const [amount,setAmount]=useState('');const selected=customers.find(c=>c.id===customer);async function submit(e:FormEvent){e.preventDefault();if(!selected)return;try{await documentsApi.createInvoice({customer_id:customer,invoice_date:date,currency:selected.default_currency,lines:[{description,quantity:'1.0000',unit_price:{amount,currency:selected.default_currency},tax_code_id:null}]});setDescription('');setAmount('');await onDone()}catch(error){onError(error instanceof Error?error.message:'Invoice creation failed.')}}return <Card><CardHeader><h2 className="font-semibold">Create invoice draft</h2></CardHeader><CardContent><form className="grid gap-3 md:grid-cols-5" onSubmit={submit}><select className="rounded-md border p-2" value={customer} onChange={e=>setCustomer(e.target.value)} required><option value="">Customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Input type="date" value={date} onChange={e=>setDate(e.target.value)} required/><Input placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)} required/><Input placeholder="Exact amount" value={amount} onChange={e=>setAmount(e.target.value)} required/><Button type="submit">Save draft</Button></form></CardContent></Card>}
